[package]
name = "adv-code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
code-timing-macros = { version = "0.0.5", features = ["release"] }
const_format = "0.2.33"
nom = "7.1.3"
grid = "0.15.0"

# Additional recommended dependencies
itertools = "0.13.0"
regex = "1.11.1"
log = "0.4.22"
strum_macros = "0.26.4"
strum = "0.26.3"
tabled = "0.17.0"

[[bin]]
name = "2024-day01-part1"
path = "src/year2024/day01/bin/part1.rs"

[[bin]]
name = "2024-day01-part2"
path = "src/year2024/day01/bin/part2.rs"

[[bin]]
name = "2024-day02-part1"
path = "src/year2024/day02/bin/part1.rs"

[[bin]]
name = "2024-day02-part2"
path = "src/year2024/day02/bin/part2.rs"

[[bin]]
name = "2024-day03-part1"
path = "src/year2024/day03/bin/part1.rs"

[[bin]]
name = "2024-day03-part2"
path = "src/year2024/day03/bin/part2.rs"

[[bin]]
name = "2024-day04-part1"
path = "src/year2024/day04/bin/part1.rs"

[[bin]]
name = "2024-day04-part2"
path = "src/year2024/day04/bin/part2.rs"
